syntax = "proto3";

package templateorder.v1;

option go_package = "template-mall/TemplateOrderServer/api/gen/templateorder/v1;templateorderv1";

enum TemplateStatus {
  TEMPLATE_STATUS_UNSPECIFIED = 0;
  TEMPLATE_STATUS_DRAFT = 1;
  TEMPLATE_STATUS_ON_SHELF = 2;
  TEMPLATE_STATUS_OFF_SHELF = 3;
}

enum PriceType {
  PRICE_TYPE_UNSPECIFIED = 0;
  PRICE_TYPE_FREE = 1;
  PRICE_TYPE_PAID = 2;
}

enum OrderType {
  ORDER_TYPE_UNSPECIFIED = 0;
  ORDER_TYPE_FREE = 1;
  ORDER_TYPE_MEMBER = 2;
  ORDER_TYPE_RETAIL = 3;
}

enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0;
  ORDER_STATUS_UNPAID = 1;
  ORDER_STATUS_DOWNLOAD_READY = 2;
  ORDER_STATUS_CANCELLED = 3;
}

enum ShelfAction {
  SHELF_ACTION_UNSPECIFIED = 0;
  SHELF_ACTION_PUBLISH = 1;
  SHELF_ACTION_UNPUBLISH = 2;
}

enum TemplateListScope {
  TEMPLATE_LIST_SCOPE_UNSPECIFIED = 0;
  TEMPLATE_LIST_SCOPE_PUBLISHED = 1;
  TEMPLATE_LIST_SCOPE_ADMIN = 2;
}
