syntax = "proto3";

package templateorder.v1;

option go_package = "template-mall/TemplateAdminWebServer/api/gen/templateorder/v1;templateorderv1";

import "enums.proto";
import "models.proto";
import "paging.proto";

message CreateTemplateRequest {
  string name = 1;
  string file_type = 2;
  int64 price_fen = 3;
  PriceType price_type = 4;
  string storage_provider = 5;
  string bucket = 6;
  string object_key = 7;
  string original_filename = 8;
  int64 file_size = 9;
  bool publish = 10;
  string cover_object_key = 11;
}

message CreateTemplateResponse {
  Template template = 1;
}

message UpdateTemplateRequest {
  string template_id = 1;
  optional string name = 2;
  optional int64 price_fen = 3;
  optional PriceType price_type = 4;
}

message UpdateTemplateResponse {
  Template template = 1;
}

message SetTemplateShelfRequest {
  string template_id = 1;
  ShelfAction action = 2;
}

message SetTemplateShelfResponse {
  Template template = 1;
}

message GetTemplateRequest {
  string template_id = 1;
}

message GetTemplateResponse {
  Template template = 1;
}

message ListTemplatesRequest {
  TemplateListScope scope = 1;
  PageRequest page = 2;
  string file_type = 3;
}

message ListTemplatesResponse {
  repeated Template templates = 1;
  PageInfo page = 2;
}
